[build]
builder = "nixpacks"

[deploy]
startCommand = "yarn start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
variables = { NODE_ENV = "production", PORT = "3000" }

[environments.staging]
variables = { NODE_ENV = "staging", PORT = "3000" }
